### ISSUE TITLE
where did you run your sql migration?

### ISSUE THREAD

**Issue by CavalloneChen** [bmvantunes/youtube-2020-march-nextjs-part4#5]
Hey Bruno, thanks for the tutorial.
One thing confused me in this tutorial is where did you use your database migration sql script? (001-helloworld.sql)

**Comment by bmvantunes** [comment]
Hello helloo :)

that runs by convention, you don't need to specify that specific file/folder anywhere. Every file inside the folder "/migrations" will run by default. If you want you can change that default folder. Example:

![sqlite-docs](https://user-images.githubusercontent.com/9042965/106651840-971cb580-658c-11eb-8c8c-8e772fa347dc.png)

**Comment by CavalloneChen** [comment]
> Hello helloo :)
> 
> 
> 
> that runs by convention, you don't need to specify that specific file/folder anywhere. Every file inside the folder "/migrations" will run by default. If you want you can change that default folder. Example:
> 
> 
> 
> ![sqlite-docs](https://user-images.githubusercontent.com/9042965/106651840-971cb580-658c-11eb-8c8c-8e772fa347dc.png)
> 
> 
> 
> 
> 
> 
Thanks!
